name: Build and Push Docker Image

# 1. O Gatilho: Roda sempre que houver um push direto na branch main
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # (Não precisa mais daquela linha "if: github.event.pull_request.merged == true")

    permissions:
      contents: read
      packages: write  # Dá permissão explícita para o token criar/atualizar imagens no GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Service Account Key File
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > serviceAccountKey.json

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest